# Generated by Django 5.1.6 on 2025-03-05 06:22

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneratedModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        help_text="Text prompt used to generate the model"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "point_cloud_file",
                    models.FileField(
                        blank=True, null=True, upload_to="models/point_clouds/"
                    ),
                ),
                (
                    "mesh_file",
                    models.FileField(blank=True, null=True, upload_to="models/meshes/"),
                ),
                (
                    "texture_file",
                    models.ImageField(
                        blank=True, null=True, upload_to="models/textures/"
                    ),
                ),
                (
                    "detail_level",
                    models.IntegerField(default=1, help_text="Level of detail (1-5)"),
                ),
                (
                    "refine_iterations",
                    models.IntegerField(
                        default=3, help_text="Number of refinement iterations"
                    ),
                ),
                ("vertex_count", models.IntegerField(default=0)),
                ("face_count", models.IntegerField(default=0)),
                (
                    "generation_time",
                    models.FloatField(
                        default=0.0,
                        help_text="Time taken to generate the model (seconds)",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GenerationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("value", models.TextField()),
                ("description", models.TextField(blank=True)),
            ],
        ),
    ]
