# Generated by Django 5.1.6 on 2025-03-05 07:39

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainedModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the trained model", max_length=100
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[("gan", "GAN"), ("diffusion", "Diffusion")],
                        default="gan",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("training", "Training"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "voxel_size",
                    models.IntegerField(
                        default=64, help_text="Voxel resolution (32, 64, 128)"
                    ),
                ),
                (
                    "latent_dim",
                    models.IntegerField(
                        default=128, help_text="Latent space dimension"
                    ),
                ),
                (
                    "batch_size",
                    models.IntegerField(
                        default=32, help_text="Batch size used during training"
                    ),
                ),
                (
                    "learning_rate",
                    models.FloatField(
                        default=0.0002, help_text="Learning rate used during training"
                    ),
                ),
                (
                    "dataset",
                    models.CharField(
                        help_text="Dataset used for training", max_length=255
                    ),
                ),
                (
                    "total_epochs",
                    models.IntegerField(default=100, help_text="Total epochs to train"),
                ),
                (
                    "current_epoch",
                    models.IntegerField(default=0, help_text="Current training epoch"),
                ),
                (
                    "model_file",
                    models.FileField(
                        blank=True, null=True, upload_to="models/trained/"
                    ),
                ),
                (
                    "config_file",
                    models.FileField(
                        blank=True, null=True, upload_to="models/configs/"
                    ),
                ),
                (
                    "generator_loss",
                    models.JSONField(
                        blank=True, help_text="Generator loss history", null=True
                    ),
                ),
                (
                    "discriminator_loss",
                    models.JSONField(
                        blank=True, help_text="Discriminator loss history", null=True
                    ),
                ),
                (
                    "training_time",
                    models.FloatField(
                        default=0.0, help_text="Total training time in seconds"
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
            ],
        ),
    ]
